apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: data-storage
      mountPath: /app/data
  volumes:
  - name: data-storage
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-2
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: data-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: data-storage
    persistentVolumeClaim:
      claimName: myclaim
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: configmap-pod
  name: configmap-pod
spec:
  containers:
  - image: nginx
    name: configmap-pod
    resources: {}
    volumeMounts:
    - name: data
      mountPath: /data
    - name: config
      mountPath: /etc/config/config.yaml
  dnsPolicy: ClusterFirst
  volumes:
  - name: data
    emptyDir: {}
  - name: config
    configMap:
      name: app-config
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-3
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: data-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: data-storage
    persistentVolumeClaim:
      claimName: static-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-4
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh","-c","sleep 3600"]
    resources: {}
    volumeMounts:
    - name: data-storage
      mountPath: /shared-data
  - image: busybox
    name: busybox-1
    command: ["/bin/sh","-c","sleep 3600"]
    resources: {}
    volumeMounts:
    - name: data-storage
      mountPath: /shared-data
  volumes:
  - name: data-storage
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: subpath-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh","-c","sleep 3600"]
    resources: {}
    volumeMounts:
    - name: data-storage
      mountPath: /mnt/storage
      subPath: data
  volumes:
  - name: data-storage
    persistentVolumeClaim:
      claimName: subpath-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: restricted-podd
  namespace: restricted-namespace
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh","-c","sleep 3600"]
    resources: {}
    volumeMounts:
    - name: data-storage
      mountPath: /mnt/storage
  volumes:
  - name: data-storage
    persistentVolumeClaim:
      claimName: restricted-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-5
spec:
  containers:
  - image: nginx
    name: nginx
    command: ["/bin/sh","-c","sleep 3600"]
    resources: {}
    volumeMounts:
    - name: host-data
      mountPath: /host-data
    - name: temp-data
      mountPath: /temp-data
  volumes:
  - name: temp-data
    emptyDir: {}
  - name: host-data
    hostPath:
      path: /mnt/host-data
      type: DirectoryOrCreate
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
